language: go
go:
  - '1.13'
  - '1.14'
  - '1.15'
  - '1.16'
  - '1.17'
sudo: false

install:
  - go get golang.org/x/lint/golint
  - go get github.com/stretchr/testify

script:
  - bash script/codecov.sh
  - go vet $(go list ./... | grep -v /examples/)
  - golint --set_exit_status ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)